<?php

namespace Creagia\Redsys\Support;

class RequestParametersFields
{
    public static $relation = [
        'DS_MERCHANT_AMOUNT' => 'amount',
        'DS_MERCHANT_AUTHORISATIONCODE' => 'authorisationCode',
        'DS_MERCHANT_COF_INI' => 'cofIni',
        'DS_MERCHANT_COF_TXNID' => 'cofTxnId',
        'DS_MERCHANT_COF_TYPE' => 'cofType',
        'DS_MERCHANT_CONSUMERLANGUAGE' => 'consumerLanguage',
        'DS_MERCHANT_CURRENCY' => 'currency',
        'DS_MERCHANT_CVV2' => 'cvv2',
        'DS_MERCHANT_DIRECTPAYMENT' => 'directPayment',
        'DS_MERCHANT_EMV3DS' => 'emv3ds',
        'DS_MERCHANT_EXPIRYDATE' => 'expiryDate',
        'DS_MERCHANT_GROUP' => 'group',
        'DS_MERCHANT_IDENTIFIER' => 'identifier',
        'DS_MERCHANT_IDOPER' => 'idOper',
        'DS_MERCHANT_MERCHANTCODE' => 'merchantCode',
        'DS_MERCHANT_MERCHANTDATA' => 'merchantData',
        'DS_MERCHANT_MERCHANTNAME' => 'merchantName',
        'DS_MERCHANT_MERCHANTURL' => 'merchantUrl',
        'DS_MERCHANT_ORDER' => 'order',
        'DS_MERCHANT_PAN' => 'pan',
        'DS_MERCHANT_PAYMETHODS' => 'payMethods',
        'DS_MERCHANT_PRODUCTDESCRIPTION' => 'productDescription',
        'DS_MERCHANT_TAX_REFERENCE' => 'taxReference',
        'DS_MERCHANT_TERMINAL' => 'terminal',
        'DS_MERCHANT_TITULAR' => 'titular',
        'DS_MERCHANT_TRANSACTIONDATE' => 'transactionDate',
        'DS_MERCHANT_TRANSACTIONTYPE' => 'transactionType',
        'DS_MERCHANT_URLKO' => 'urlOk',
        'DS_MERCHANT_URLOK' => 'urlKo',
        'DS_XPAYDATA' => 'xpayData',
        'DS_XPAYORIGEN' => 'xpayOrigen',
        'DS_XPAYTYPE' => 'xpayType',
        'DS_MERCHANT_SHIPPINGADDRESSPYP' => 'shippingAddressPyp',
        'DS_MERCHANT_MERCHANTDESCRIPTOR' => 'merchantDescriptor',
        'DS_MERCHANT_PERSOCODE' => 'persoCode',
        'DS_MERCHANT_MATCHINGDATA' => 'matchingData',
        'DS_ACQUIRER_IDENTIFIER' => 'acquirerIdentifier',
        'DS_MERCHANT_MPIEXTERNAL' => 'mpiExternal',
        'DS_MERCHANT_CUSTOMER_MOBILE' => 'customerMobile',
        'DS_MERCHANT_CUSTOMER_MAIL' => 'customerMail',
        'DS_MERCHANT_P2F_EXPIRYDATE' => 'p2fExpiryDate',
        'DS_MERCHANT_CUSTOMER_SMS_TEXT' => 'customerSmsText',
        'DS_MERCHANT_P2F_XMLDATA' => 'p2fXmlData',
        'DS_MERCHANT_DCC' => 'dcc',
        'DS_MERCHANT_EXCEP_SCA' => 'excepSca',
        'DS_MERCHANT_OTA' => 'ota',
    ];
}
